[theme]
base = "dark"
baseFontSize = 16

# General color setup
textColor = "#e2e8f0" # This is the text color of the app
primaryColor = "#9CB080" # This is the primary color of elements (radio, checkbox, slider, etc.)
backgroundColor = "#141a1d" # This is the background color of the app
secondaryBackgroundColor = "#000000" # This is the background color of elements (browse, checkbox, fields, etc.)
codeTextColor = "#9CB080" # This is the text color of code blocks

# Widgets
showWidgetBorder = true
borderColor = "#777777"